### ISSUE TITLE
impossible de compiler avec nouvelle version de yarn

### ISSUE THREAD

**Issue by f5nlg** [spotnik-ham/gui#15]
probleme dans le keypad.js avec styled-jsx

**Comment by f5nlg** [comment]
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-xo-react@0.12.0" has unmet peer dependency "eslint@>=3".
warning " > eslint-plugin-react@7.0.1" has unmet peer dependency "eslint@^3.0.0".
[4/4] Building fresh packages...
Done in 22.44s.
next build
> Failed to build on /tmp/8dda15c4-7bdf-45dd-bc17-75dd31721de4
{ Error: ./pages/keypad.js?entry
Module build failed: Error: /opt/spotnik/gui/pages/keypad.js?entry: Nesting detected at 5:110. Unfortunately nesting is not supported by styled-jsx.
    at Array.disableNestingPlugin (/opt/spotnik/gui/node_modules/styled-jsx/dist/lib/style-transform.js:19:13)
    at proxy (/opt/spotnik/gui/node_modules/stylis/stylis.js:1108:20)
    at compile (/opt/spotnik/gui/node_modules/stylis/stylis.js:629:10)
    at compile (/opt/spotnik/gui/node_modules/stylis/stylis.js:279:17)
    at compile (/opt/spotnik/gui/node_modules/stylis/stylis.js:313:17)
    at stylis (/opt/spotnik/gui/node_modules/stylis/stylis.js:1076:16)
    at transform (/opt/spotnik/gui/node_modules/styled-jsx/dist/lib/style-transform.js:100:10)
    at PluginPass.exit (/opt/spotnik/gui/node_modules/styled-jsx/dist/babel.js:267:59)
    at newFn (/opt/spotnik/gui/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/opt/spotnik/gui/node_modules/babel-traverse/lib/path/context.js:76:18)
 @ multi ./pages/keypad.js?entry
    at /opt/spotnik/gui/node_modules/next/dist/server/build/index.js:182:21
    at /opt/spotnik/gui/node_modules/webpack/lib/Compiler.js:272:15
    at Compiler.emitRecords (/opt/spotnik/gui/node_modules/webpack/lib/Compiler.js:367:37)
    at /opt/spotnik/gui/node_modules/webpack/lib/Compiler.js:265:12
    at /opt/spotnik/gui/node_modules/webpack/lib/Compiler.js:360:11
    at next (/opt/spotnik/gui/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/opt/spotnik/gui/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/opt/spotnik/gui/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/opt/spotnik/gui/node_modules/webpack/lib/Compiler.js:357:8)
    at Compiler.<anonymous> (/opt/spotnik/gui/node_modules/webpack/lib/Compiler.js:352:14)
  errors: 
   [ './pages/keypad.js?entry\nModule build failed: Error: /opt/spotnik/gui/pages/keypad.js?entry: Nesting detected at 5:110. Unfortunately nesting is not supported by styled-jsx.\n    at Array.disableNestingPlugin (/opt/spotnik/gui/node_modules/styled-jsx/dist/lib/style-transform.js:19:13)\n    at proxy (/opt/spotnik/gui/node_modules/stylis/stylis.js:1108:20)\n    at compile (/opt/spotnik/gui/node_modules/stylis/stylis.js:629:10)\n    at compile (/opt/spotnik/gui/node_modules/stylis/stylis.js:279:17)\n    at compile (/opt/spotnik/gui/node_modules/stylis/stylis.js:313:17)\n    at stylis (/opt/spotnik/gui/node_modules/stylis/stylis.js:1076:16)\n    at transform (/opt/spotnik/gui/node_modules/styled-jsx/dist/lib/style-transform.js:100:10)\n    at PluginPass.exit (/opt/spotnik/gui/node_modules/styled-jsx/dist/babel.js:267:59)\n    at newFn (/opt/spotnik/gui/node_modules/babel-traverse/lib/visitors.js:276:21)\n    at NodePath._call (/opt/spotnik/gui/node_modules/babel-traverse/lib/path/context.js:76:18)\n @ multi ./pages/keypad.js?entry' ],
  warnings: [] }
Makefile:6: recipe for target 'setup' failed
make: *** [setup] Error 1

**Comment by sonnyp** [comment]
réparé https://github.com/spotnik-ham/gui/commit/e4d2de7f7f8ac42e29cbbf96bb913a20b1e34904
